CREATE DATABASE `atv`;
USE atv;

CREATE TABLE `info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `vetor` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(45) NOT NULL,
  `ITENS` mediumtext NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `endereco` (
  `USER_ID` int(11) NOT NULL,
  `RUA` varchar(120) NOT NULL,
  `NUMERO` int(11) NOT NULL,
  `COMPLEMENTO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `fk_table1_USER1` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `valor` (
  `INFO_ID` int(11) NOT NULL,
  `VETOR_ID` int(11) NOT NULL,
  `VALOR` double NOT NULL,
  PRIMARY KEY (`INFO_ID`,`VETOR_ID`),
  KEY `fk_VALOR_VETOR1` (`VETOR_ID`),
  CONSTRAINT `fk_VALOR_INFO` FOREIGN KEY (`INFO_ID`) REFERENCES `info` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_VALOR_VETOR1` FOREIGN KEY (`VETOR_ID`) REFERENCES `vetor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `vetor_has_user` (
  `VETOR_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`VETOR_ID`,`USER_ID`),
  KEY `fk_VETOR_has_USER_USER1` (`USER_ID`),
  CONSTRAINT `fk_VETOR_has_USER_USER1` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_VETOR_has_USER_VETOR1` FOREIGN KEY (`VETOR_ID`) REFERENCES `vetor` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
